package com.iyex.hotelmgt.domain.account;

public enum Permission {
    USER_CREATE,   USER_READ,   USER_UPDATE,   USER_DELETE,
    ADDRESS_CREATE, ADDRESS_READ, ADDRESS_UPDATE, ADDRESS_DELETE,
    COUNTRY_CREATE, COUNTRY_READ, COUNTRY_UPDATE, COUNTRY_DELETE,
    REGION_CREATE,  REGION_READ,  REGION_UPDATE,  REGION_DELETE,
    CITY_CREATE,    CITY_READ,    CITY_UPDATE,    CITY_DELETE,
    SUB_CITY_CREATE, SUB_CITY_READ, SUB_CITY_UPDATE, SUB_CITY_DELETE,
    DISTRICT_CREATE,DISTRICT_READ,DISTRICT_UPDATE,DISTRICT_DELETE,
    BOOKING_CREATE, BOOKING_READ, BOOKING_UPDATE, BOOKING_DELETE,
    HOTEL_CREATE,   HOTEL_READ,   HOTEL_UPDATE,   HOTEL_DELETE,

    RATING_CREATE,  RATING_READ,  RATING_UPDATE,  RATING_DELETE,
    REVIEW_CREATE,  REVIEW_READ,  REVIEW_UPDATE,  REVIEW_DELETE,
    SERVICE_CREATE, SERVICE_READ, SERVICE_UPDATE, SERVICE_DELETE;
}
